name: Stable Theme Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  TZ: Asia/Shanghai

jobs:
  theme_test:
    name: Hexo build & deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4
      with:
        repository: 'blleng/lx-test'
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install -g hexo-cli
        npm ci
        git clone -b dev https://github.com/blleng/hexo-theme-lx/ themes/lx

    - name: Generate files
      run: |
        npx hexo clean
        npx hexo generate

    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-page
        token: ${{ secrets.LX_STABLE_REPO }}
        repository-name: blleng/lx-test
        git-config-name: blleng
        git-config-email: lengbl@outlook.com
